name: Cypress Tests on PR

on:
  pull_request:
    branches: [develop]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install client dependencies
        run: cd client && npm ci

      - name: Install Cypress binary
        run: npx cypress install

      - name: Start dev server
        run: cd client && npm run dev -- --host &
        shell: bash

      - name: Wait for dev server
        run: npx wait-on http://localhost:5173

      - name: Run Cypress tests
        run: npx cypress run-ct
