name: Cypress Tests on PR

on:
  pull_request:
    branches: [develop]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install client dependencies
        run: cd client && npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: cd client && npm run dev -- --host
          wait-on: http://localhost:5173
          wait-on-timeout: 60 
