name: Cypress Tests on PR

on:
  pull_request:
    branches: [develop]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev -- --host
          wait-on: http://localhost:5173
          wait-on-timeout: 60
        env:
          # If your Cypress config uses any environment variables, define them here
          # Example: CYPRESS_BASE_URL: http://localhost:5173
